# fly.toml file generated for the-wall-api-bun on 2022-07-06T23:42:51+03:00

app = "the-wall-api-bun"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  DB_FILE = "/data/db.sqlite"
  PORT=8080

[mounts]
  destination = "/data"
  source = "the_wall_api_bun_data"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
